[rename]
"/process/name" = "Process Name"
"/process/executable" = "Process Executable"
"/process/parent/name" = "Parent Name"
"/process/parent/executable" = "Parent Executable"
"/process/command_line" = "Process Command Line"
"/process/parent/command_line" = "Parent Command Line"
"/file/name" = "File Name"
"/file/path" = "File Path"
"/file/original/name" = "Original File Name"
"/file/original/path" = "Original File Path"

[format]
"/process/command_line" = "block"
"/process/parent/command_line" = "block"
