[rename]
"/process/name" = "Process Name"
"/process/executable" = "Process Executable"
"/process/parent/name" = "Parent Name"
"/process/parent/executable" = "Parent Executable"
"/process/command_line" = "Process Command Line"
"/process/parent/command_line" = "Parent Command Line"
"/file/name" = "File Name"
"/file/path" = "File Path"
"/file/hash/sha1" = "SHA1 Hash"
"/file/Ext/original/name" = "Original File Name"
"/file/Ext/original/path" = "Original File Path"
"/sentinel_one/activity/description/primary" = "S1 Action Taken"
"/sentinel_one/activity/data/threat/classification/name" = "Classification"
"/process/code_signature/subject_name" = "Process Signer"
"/registry/path" = "Registry Path"
"/registry/value" = "Registry Value"
"/registry/data/strings" = "Registry Strings"
"/file/extension" = "File Extension"
"/dns/question/name" = "DNS Question"
"/dns/question/type" = "DNS Type"
"/azure/signinlogs/operation_name" = "Azure Operation"
"/azure/signinlogs/identity" = "Azure Identity"
"/azure/signinlogs/properties/app_display_name" = "Azure Application"
"/user_agent/original" = "User Agent"
"/source/address" = "IP Address"
"/source/as/organization/name" = "Source ASN"
"/source/geo/city_name" = "Source City"
"/source/geo/region_name" = "Source Region"
"/source/geo/country_name" = "Source Country"
"/source/enrich/vpn" = "VPN Usage"
"/source/enrich/tor" = "TOR Usage"
"/source/enrich/proxy" = "Proxy Usage"
"/Events/event/action" = "Event Action"
"/Events/destination/ip" = "Destination IP"
"/Events/file/name" = "File Name"
"/Events/file/path" = "File Path"
"/Events/file/Ext/original/name" = "Original File Name"
"/Events/file/Ext/original/extension" = "Original File Extension"
"/Events/file/Ext/original/path" = "Original File Path"
"/Events/process/name" = "Process Name"
"/Events/process/executable" = "Process Executable"
"/Events/process/working_directory" = "Process Working Directory"
"/process/working_directory" = "Process Working Directory"
"/Events/process/code_signature/subject_name" = "Process Signer"
"/Events/process/parent/name" = "Parent Name"
"/Events/process/parent/executable" = "Parent Executable"
"/Events/process/command_line" = "Process Command Line"
"/Events/process/parent/command_line" = "Parent Command Line"
"/o365/audit/Data" = "Audit Data"
"/o365/audit/Source" = "Audit Source"
"/o365/audit/ObjectId" = "Object ID"
"/o365/audit/UserId" = "User ID"
"/o365/audit/SiteUrl" = "Site URL"
"/user/name" = "User"
"/user/target/name" = "Target User"
"/host/hostname" = "Host"
"/host/name" = "Host"
"/o365/audit/ModifiedProperties/Role_DisplayName/NewValue" = "New Role Name"
"/azure/auditlogs/properties/initiated_by/app/displayName" = "Initiated By App"
"/azure/auditlogs/properties/initiated_by/user/userPrincipalName" = "Initiated By User"
"/group/name" = "Group Name"
"/aws/cloudtrail/user_identity/arn" = "User ARN"
"/aws/cloudtrail/flattened/request_parameters/alarmNames" = "Alarm Names"
"/okta/actor/alternate_id" = "Actor Alt ID"
"/okta/target/alternate_id" = "Target Alt ID"
"/okta/display_message" = "Message"
"/okta/client/ip" = "Client IP"
"/okta/security_context/as/organization/name" = "Source ASN"
"/okta/debug_context/debug_data/request_uri" = "Request URI"
"/okta/outcome/reason" = "Outcome Reason"
"/okta/outcome/result" = "Outcome Result"
"/file/code_signature/subject_name" = "File Signer"
"/Responses/action/action" = "Response Action"
"/Responses/message" = "Response Message"
"/Events/registry/path" = "Registry Path"
"/Events/registry/value" = "Registry Value"
"/Events/registry/data/strings" = "Registry Strings"
"/dll/name" = "DLL Name"
"/dll/path" = "DLL Path"
"/dll/Ext/code_signature/subject_name" = "DLL Signer"
"/dll/pe/original_file_name" = "Original DLL Name"
"/process/Ext/effective_parent/name" = "Effective Parent Name"
"/process/Ext/effective_parent/executable" = "Effective Parent Executable"
"/threat/indicator/file/hash/sha1" = "SHA1 Hash"
"/sentinel_one/threat/name" = "File Name"
"/sentinel_one/threat/originator_process" = "Originator Process"
"/sentinel_one/threat/publisher/name" = "File Publisher"
"/sentinel_one/threat/indicators/description" = "S1 Threat Indicators"
"/sentinel_one/threat/classification" = "Classification"
"/Effective_process/name" = "Effective Process Name"
"/Effective_process/executable" = "Effective Process Executable"


[format]
"/process/command_line" = "block"
"/process/parent/command_line" = "block"
"/sentinel_one/activity/description/primary" = "block"
"/sentinel_one/threat/malicious_process_arguments" = "block"
"/registry/data/strings" = "block"
"/message" = "block"
"/user_agent/original" = "block"
"/Events/process/command_line" = "block"
"/Events/process/parent/command_line" = "block"
"/o365/audit/Data" = "block"
"/Responses/message" = "block"
"/Events/registry/data/strings" = "block"
"/sentinel_one/threat/indicators/description" = "block"

[unique_prefix]
"/process/command_line" = "$"
"/process/parent/command_line" = "$"

[compound.templates]
"/source/network_session" = [
	"try this {{ source_ip }} on {{ source_port }}",
	"then this {{ sourc_ip }}",
]

[compound.variables]
"source_ip" = "/source/ip"
"source_port" = "/source/port"
