[rename]
"/process/name" = "Process Name"
"/process/executable" = "Process Executable"
"/process/parent/name" = "Parent Name"
"/process/parent/executable" = "Parent Executable"
"/process/command_line" = "Process Command Line"
"/process/parent/command_line" = "Parent Command Line"
"/file/name" = "File Name"
"/file/path" = "File Path"
"/file/hash/sha1" = "SHA1 Hash"
"/file/Ext/original/name" = "Original File Name"
"/file/Ext/original/path" = "Original File Path"
"/sentinel_one/activity/description/primary" = "Action Taken"
"/sentinel_one/activity/data/threat/classification/name" = "Classification"
"/process/code_signature/subject_name" = "Process Signer"
"/registry/path" = "Registry Path"
"/registry/value" = "Registry Value"
"/registry/data/strings" = "Registry Strings"
"/file/extension" = "File Extension"

[format]
"/process/command_line" = "block"
"/process/parent/command_line" = "block"
"/sentinel_one/activity/description/primary" = "block"
"/sentinel_one/threat/malicious_process_arguments" = "block"
"/registry/data/strings" = "block"

[unique_prefix]
"/process/command_line" = "$"
"/process/parent/command_line" = "$"

[compound.templates]
"/source/network_session" = [
	"try this {{ source_ip }} on {{ source_port }}",
	"then this {{ sourc_ip }}",
]

[compound.variables]
"source_ip" = "/source/ip"
"source_port" = "/source/port"
