["__USER__"]
path_set = [
	"/winlog/event_data/Detection User",
	"/sentinel_one/threat/process_user",
	"/user/name",
	"/user/target/name",
]
prefix_primary = "with user"
prefix_secondary = "Related Users"
plural_fallback = "with multiple users"
app_display = "Users"

["__HOST__"]
path_set = [
	"/host/hostname",
	"/host/name",
]
prefix_primary = "on host"
prefix_secondary = "Affected Hosts"
plural_fallback = "on multiple hosts"
app_display = "Hosts"

["__DOMAIN__"]
path_set = [
	"/user/domain"
]
prefix_primary = "on domain"
prefix_secondary = "Affected Domains"
plural_fallback = "on multiple domains"
app_display = "Domain"

["__TENANT__"]
path_set = [
	"/todyl/organization/name"
]
prefix_primary = "in tenant"
prefix_secondary = "Affected Tenants"
plural_fallback = "in multiple tenants"
app_display = "Tenant"
