display_as = "AWS Activity"
surrounding_events = false
scopes = [
	"__TENANT__",
	"__DOMAIN__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time to suggest user account compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [ ]
data = [
	"/event.action",
	"/user/name",
	"/aws/cloudtrail/user_identity/arn",
	"/user/target/name",
	"/aws/cloudtrail/flattened/request_parameters/alarmNames",
	"/group/name",
	"/aws/cloudtrail/flattened/request_parameters/groupDescription",
	"/source/address",
	"/source/geo",
	"/user_agent/original",
]
