display_as = "Azure Sign In Activity"
surrounding_events = true
siem_link = "https://kibana.todyl.com/app/discover#/view/22fa5cc5-2319-4681-9e3d-241670f99df4?_g=()"
scopes = [
	"__DOMAIN__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time to suggest user account compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Log out of all active sessions, reset the credentials of the end user, and ensure MFA is enabled/reset."
]
data = [
	"/event.action",
	"/user/name",
	"/user/target/name",
	"/azure/signinlogs/operation_name",
	"/azure/auditlogs/operation_name",
	"/azure/signinlogs/identity",
	"/azure/signinlogs/properties/app_display_name",
	"/azure/auditlogs/properties/initiated_by/app/displayName",
	"/azure/auditlogs/properties/initiated_by/user/userPrincipalName",
	"/o365/audit/ObjectId",
	"/o365/audit/UserId",
	"/o365/audit/FileData/FileName",
	"/o365/audit/FileData/FilePath",
	"/o365/audit/FileData/SHA256",
	"/o365/audit/FileData/MalwareFamily",
	"/o365/audit/EventSource",
	"/o365/audit/SiteUrl",
	"/url/original",
	"/o365/audit/Parameters/Role",
	"/o365/audit/Parameters/SecurityGroup",
	"/o365/audit/ModifiedProperties/Role_DisplayName/NewValue",
	"/source/address",
	"/source/geo",
	# "/source/address",
	# "/source/as/organization/name",
	# "/source/geo/city_name",
	# "/source/geo/region_name",
	# "/source/geo/country_name",
	"/source/enrich/vpn",
	"/source/enrich/hosting",
	"/user_agent/original",
]
