display_as = "Cisco Duo Activity"
surrounding_events = false
scopes = [
	"__DOMAIN__",
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time to suggest user account compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity is expected and approved."
]
data = [
	"/event.action",
	"/user/name",
	"/cisco_duo/admin/action_performed_on",
	"/cisco_duo/admin/flattened/admin_email",
	"/cisco_duo/admin/flattened/policy",

	"/cisco_duo/auth/application/name",	

	"/source/ip",
	"/source/address",
	"/source/geo",
]

