display_as = "Correlated Activity"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity is expected and approved.",
]
data = [
	"/event.action",
	"/dns/question/name",
	"/dns/question/type",
	
	"/winlog/logon/failure/reason",

	"/process/name",
	"/process/executable",
	"/process/working_directory",
	"/process/code_signature/subject_name",
	"/process/parent/name",
	"/process/parent/executable",
	"/process/command_line",
	"/process/parent/command_line",

# ---- Suspicious Logon From an Abused Hosting Provider ---
	"/source/ip",
	"/source/address",
	"/source/geo",
	"/source/enrich/hosting",
	"/user_agent/original",

]
