display_as = "Endpoint Network Activity"
surrounding_events = true
siem_link = "https://kibana.todyl.com/app/discover#/view/8829d875-364e-40d2-83b9-73b7febdde19?_g=()"
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity is expected and approved.",
]
# Missing:
# Destination IP
data = [
	"/event.action",
	"/dns/question/name",
	"/dns/question/type",
	"/destination/ip",
	"/destination/address",
	"/destination/geo",
	"/process/name",
	"/process/executable",
	"/process/code_signature",
	"/process/command_line",
	"/message"
]
