display_as = "Endpoint Library Activity"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/event.action",
	"/dll/name",
	"/dll/path",
	"/dll/code_signature/subject_name",
	"/dll/pe/original_file_name",
	"/process/name",
	"/process/executable",
	"/process/code_signature/subject_name",
	"/process/command_line",
	"/process/parent/command_line",
]
