display_as = "Endpoint File Event"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/event.action",
	"/file/name",
	"/file/Ext/original/name",
	"/file/path",
	"/file/extension",
	"/file/Ext/original/path",
	"/process/name",
	"/process/executable",
	"/process/code_signature/subject_name",
	"/process/command_line",
	"/process/parent/command_line",
]
