display_as = "Endpoint File Event"
rca_footer = [
	"There are no additional alerts at this time which suggest user or host compromise.",
]
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/event.action",
	"/file/name",
	"/file/path",
	"/file/Ext/original/name",
	"/file/Ext/original/path",
	"/process/name",
	"/process/executable",
]
