display_as = "Google Workspace Activity"
surrounding_events = false
scopes = [
	"__DOMAIN__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time to suggest user account compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"[TODO]"
]
data = [
	"/event.action",
	"/user/name",
	"/json/actor/email",
	"/user/target/name",
	"/google_workspace/admin/application/name",
	"/google_workspace/admin/setting/name",
	"/google_workspace/admin/user_defined_setting/name",
	"/google_workspace/admin/new_value",



	"/json/events/type",
	"/json/events/parameters/name",
	"/json/events/parameters/value",

	"/source/ip",
	"/source/as/organization/name",
	"/source/geo/city_name",
	"/source/geo/region_name",
	"/source/geo/country_name",

]

