display_as = "Malicious Behavior"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/Responses/action/action",
	"/Responses/message",
	"/Events/event/action",
	"/Events/destination/ip",

	"/Events/file/name",
	"/Events/file/path",
	"/Events/file/Ext/original/name",
	"/Events/file/Ext/original/extension",
	"/Events/file/Ext/original/path",

	"/Events/dll/name",
	"/Events/dll/path",

	"/Events/process/name",
	"/Events/process/executable",
	"/Events/process/code_signature/subject_name",
	"/Events/process/working_directory",
	"/Events/process/Ext/api/summary",
	"/Events/process/Ext/api/metadata/target_address_path",
	"/Events/process/Ext/api/parameters/hook_module",

	"/Events/process/parent/name",
	"/Events/process/parent/executable",
	"/Events/process/parent/code_signature/subject_name",

	"/Target/process/name",
	"/Target/process/executable",
	"/Target/process/Ext/memory_region/strings",

	"/Events/Persistence/args",
	"/Events/Persistence/path",

	"/Events/process/command_line",
	"/Events/process/parent/command_line",
	"/Events/registry/path",
	"/Events/registry/value",
	"/Events/registry/data/strings",
]
