display_as = "Malicious Behavior"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/Events/event/action",
	"/Events/destination/ip",

	"/Events/file/name",
	"/Events/file/path",
	"/Events/file/Ext/original/name",
	"/Events/file/Ext/original/extension",
	"/Events/file/Ext/original/path",

	"/Events/process/name",
	"/Events/process/executable",
	"/Events/process/working_directory",
	"/Events/process/code_signature/subject_name",

	"/Events/process/parent/name",
	"/Events/process/parent/executable",

	"/Events/process/command_line",
	"/Events/process/parent/command_line",
]
