display_as = "Malware"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,\n\nThere are currently [X out of Y vendors](__LINK__) on VirusTotal reporting this file as malicious."
rca_footer = "There are no additional alerts at this time to suggest user or host compromise."
rns = [
	"Implement \"Prevent\" mode for malware alerts within the Todyl customer portal.",
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = []
data = [
	"/process/name",
	"/process/executable",
	"/process/parent/executable",
	"/file/name",
	"/file/path",
	"/file/hash/sha256",
	"/file/Ext/quarantine_message",
	# "/file/Ext/quarantine_path",
	"/file/code_signature",
	"/process/command_line",
	"/process/parent/command_line",
]
