display_as = "Malware"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time to suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [ 
	"[TODO]" 
]
data = [
	"/process/name",
	"/process/executable",
	"/process/parent/executable",
	"/file/name",
	"/file/path",
	"/file/hash/sha256",
	"/file/Ext/quarantine_message",
	"/file/Ext/quarantine_path",
	"/file/Ext/quarantine_result",
	"/file/code_signature/subject_name",
	"/process/command_line",
	"/process/parent/command_line",
]
