display_as = "Malware"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,\n\nThere are currently [X out of Y vendors](__LINK__) on VirusTotal reporting this file as malicious."
rca_footer = "There are no additional alerts at this time to suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [ 
	"Ensure this activity is expected and approved."
]
data = [
	"/event.action",
	"/process/name",
	"/process/executable",
	"/process/parent/name",
	"/process/parent/executable",

	"/file/name",
	"/file/path",
	"/file/hash/sha256",
	"/file/code_signature",
	"/file/pe/original_file_name",
	"/file/pe/product",
	"/file/pe/company",

	"/process/command_line",
	"/process/parent/command_line",
]
