display_as = "Memory Threat Event"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,\n\nThere are currently [X out of Y vendors](__LINK__) on VirusTotal reporting this process as malicious."
rca_footer = "There are no additional alerts at this time to suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity is expected and approved.",
]
data = [
	"/event.code",

	"/process/name",
	"/process/executable",
	"/process/working_directory",
	"/process/code_signature",

	"/process/Ext/memory_region/allocation_protection",
	"/process/Ext/memory_region/allocation_type",
	"/process/Ext/memory_region/region_protection",
	"/process/Ext/memory_region/region_state",

	"/process/parent/name",
	"/process/parent/executable",
	"/process/parent/code_signature",
	"/process/Ext/effective_parent/name",
	"/process/Ext/effective_parent/executable",
	"/Effective_process/name",
	"/Effective_process/executable",

	"/process/command_line",
	"/process/parent/command_line",
]
