display_as = "Msft Defender for Endpoint Event"
surrounding_events = false
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
scopes = [
	"__HOST__",
	"__USER__",
]
rns = [
	"For more information, please visit the Windows Defender portal.",
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/microsoft/defender_endpoint/threatName",
	"/microsoft/defender_endpoint/evidence/detectionStatus",
	"/file/name",
	"/file/path",
	"/file/hash/sha256",
	"/microsoft/defender_endpoint/evidence/parentProcessFileName",
	"/microsoft/defender_endpoint/evidence/parentProcessFilePath",

	"/message",
	"/process/command_line",
]
