display_as = "Msft M365 Defender Event"
surrounding_events = false
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
scopes = [
	"__HOST__",
	"__USER__",
]
rns = [
	"For more information, please visit the Windows Defender portal.",
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/json/alerts/entities/detectionStatus",	
	"/json/alerts/entities/fileName",
	"/json/alerts/entities/filePath",
	"/json/alerts/entities/parentProcessFileName",
	"/json/alerts/entities/parentProcessFilePath",
	"/json/alerts/entities/processCommandLine",


	"/message",
	"/json/alerts/description",
]
