display_as = "Office 365 Activity"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/event.action",
	"/user/name",
	"/user/target/name",
	"/o365/audit/Source",
	"/o365/audit/Data",	
	"/azure/signinlogs/operation_name",
	"/azure/auditlogs/operation_name",
	"/azure/signinlogs/identity",
	"/azure/signinlogs/properties/app_display_name",
	"/azure/auditlogs/properties/initiated_by/app/displayName",
	"/azure/auditlogs/properties/initiated_by/user/userPrincipalName",
	"/o365/audit/ObjectId",
	"/o365/audit/UserId",
	"/o365/audit/FileData/FileName",
	"/o365/audit/FileData/FilePath",
	"/o365/audit/FileData/SHA256",
	"/o365/audit/FileData/MalwareFamily",
	"/o365/audit/EventSource",
	"/o365/audit/SiteUrl",
	"/url/original",
	"/o365/audit/Parameters/Role",
	"/o365/audit/Parameters/SecurityGroup",
	"/o365/audit/ModifiedProperties/Role_DisplayName/NewValue",
	"/source/ip",
	"/source/address",
	"/source/geo",
	"/source/enrich/vpn",
	"/source/enrich/hosting",
	"/user_agent/original",
]
