display_as = "Ransomware Event"
surrounding_events = true
scopes = [
	"__HOST__",
	"__USER__",
]
rca_filler = "Per our investigation,\n\nThere are currently [X out of Y vendors](__LINK__) on VirusTotal reporting this process as malicious."
rca_footer = "There are no additional alerts at this time to suggest user or host compromise."
rns = [
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [ ]
data = [

]
