display_as = "SentinelOne AV Event"
surrounding_events = false
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
scopes = [
	"__HOST__",
	"__USER__",
]
rns = [
	"For more information, please visit the SentinelOne Portal",
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/file/name",
	"/file/path",
	"/file/hash/sha1",
	"/sentinel_one/activity/data/threat/classification/name",
	"/sentinel_one/activity/description/primary",
	"/sentinel_one/threat/malicious_process_arguments",
]
