display_as = "SentinelOne AV Event"
surrounding_events = false
rca_filler = "Per our investigation,"
rca_footer = "There are no additional alerts at this time which suggest user or host compromise."
scopes = [
	"__HOST__",
	"__USER__",
]
rns = [
	"For more information, please visit the SentinelOne Portal",
	"If this activity is not expected, please reach out to the MXDR team for further investigation.",
]
rns_tp = [
	"Ensure this activity was expected and approved.",
]
data = [
	"/sentinel_one/threat/incident/status",
	"/sentinel_one/threat/mitigation_status/action",

	"/file/name",
	"/sentinel_one/threat/name",

	"/file/path",
	"/threat/indicator/file/path",

	"/file/hash/sha1",
	"/threat/indicator/file/hash/sha1",

	"/sentinel_one/threat/publisher/name",

	"/process/name",
	"/sentinel_one/threat/originator_process",

	"/sentinel_one/activity/data/threat/classification/name",
	"/sentinel_one/threat/classification",
	"/sentinel_one/activity/description/primary",
	"/sentinel_one/threat/malicious_process_arguments",
	"/sentinel_one/threat/indicators/description",
]
